export const DISTROKID_LANGUAGES = [
  { value: "1", label: "Arabic" },
  { value: "41", label: "Bosnian" },
  { value: "40", label: "Bulgarian" },
  { value: "2", label: "Cantonese" },
  { value: "3", label: "Catalan" },
  { value: "4", label: "Chinese (Simplified)" },
  { value: "5", label: "Chinese (Traditional)" },
  { value: "6", label: "Croatian" },
  { value: "7", label: "Czech" },
  { value: "8", label: "Danish" },
  { value: "9", label: "Dutch" },
  { value: "10", label: "English" },
  { value: "11", label: "Estonian" },
  { value: "12", label: "Finnish" },
  { value: "13", label: "French" },
  { value: "14", label: "German" },
  { value: "15", label: "Greek" },
  { value: "16", label: "Hebrew" },
  { value: "42", label: "Hindi" },
  { value: "17", label: "Hungarian" },
  { value: "18", label: "Icelandic" },
  { value: "19", label: "Indonesian" },
  { value: "20", label: "Italian" },
  { value: "21", label: "Japanese" },
  { value: "22", label: "Korean" },
  { value: "23", label: "Lao" },
  { value: "24", label: "Latvian" },
  { value: "25", label: "Lithuanian" },
  { value: "26", label: "Malay" },
  { value: "27", label: "Norwegian" },
  { value: "44", label: "Persian" },
  { value: "28", label: "Polish" },
  { value: "29", label: "Portuguese" },
  { value: "43", label: "Punjabi" },
  { value: "30", label: "Romanian" },
  { value: "31", label: "Russian" },
  { value: "32", label: "Slovak" },
  { value: "33", label: "Spanish" },
  { value: "45", label: "Swahili" },
  { value: "34", label: "Swedish" },
  { value: "35", label: "Tagalog" },
  { value: "36", label: "Thai" },
  { value: "37", label: "Turkish" },
  { value: "38", label: "Ukrainian" },
  { value: "39", label: "Vietnamese" }
];

export const DISTROKID_GENRES = [
  { value: "58", label: "Afrobeat" },
  { value: "59", label: "Afropop" },
  { value: "1", label: "Alternative" },
  { value: "2", label: "Big Band" },
  { value: "3", label: "Blues" },
  { value: "4", label: "Children's Music" },
  { value: "5", label: "Christian/Gospel" },
  { value: "33", label: "Classical" },
  { value: "6", label: "Comedy" },
  { value: "61", label: "Contemporary Latin" },
  { value: "7", label: "Country" },
  { value: "8", label: "Dance" },
  { value: "9", label: "Electronic" },
  { value: "10", label: "Fitness & Workout" },
  { value: "11", label: "Folk" },
  { value: "12", label: "French Pop" },
  { value: "13", label: "German Folk" },
  { value: "14", label: "German Pop" },
  { value: "16", label: "Hip Hop/Rap" },
  { value: "17", label: "Holiday" },
  { value: "19", label: "J-Pop" },
  { value: "20", label: "Jazz" },
  { value: "21", label: "K-Pop" },
  { value: "22", label: "Latin" },
  { value: "64", label: "Latin House" },
  { value: "62", label: "Latin Jazz" },
  { value: "56", label: "Latin Urban" },
  { value: "65", label: "Maskandi" },
  { value: "15", label: "Metal" },
  { value: "23", label: "New Age" },
  { value: "24", label: "Pop" },
  { value: "63", label: "Pop in Spanish" },
  { value: "34", label: "Punk" },
  { value: "25", label: "R&B/Soul" },
  { value: "26", label: "Reggae" },
  { value: "27", label: "Rock" },
  { value: "60", label: "Rock en Español" },
  { value: "28", label: "Singer/Songwriter" },
  { value: "29", label: "Soundtrack" },
  { value: "30", label: "Spoken Word" },
  { value: "31", label: "Vocal" },
  { value: "32", label: "World" },
  { value: "66", label: "Xigaza" }
];

export const DISTROKID_PERFORMER_ROLES = [
  "Background vocals",
  "Banjo",
  "Bass",
  "Bass drum (concert)",
  "Bass drum (kick)",
  "Bass guitar (all types)",
  "Bass guitar (electric)",
  "Basset horn",
  "Bassoon",
  "Bell tree",
  "Bongos",
  "Brass instrument",
  "Cello",
  "Clarinet",
  "Claves",
  "Clavinet",
  "Congas",
  "Contrabass",
  "Cowbell",
  "Cymbals",
  "Didgeridoo",
  "Djembe",
  "Dobro guitar",
  "Double bass",
  "Drum machine",
  "Drums",
  "Electric organ",
  "English horn",
  "Fiddle",
  "Flugelhorn",
  "Flute",
  "French horn",
  "Gong",
  "Guitar (acoustic)",
  "Guitar (any type)",
  "Guitar (electric)",
  "Harmonica",
  "Harpsichord",
  "Kazoo",
  "Keyboard",
  "Lute",
  "Mandolin",
  "Marimba",
  "Melodica",
  "Oboe",
  "Ocarina",
  "Other instrument",
  "Pan flute",
  "Percussion instrument",
  "Performer",
  "Piano",
  "Piccolo",
  "Pipe organ",
  "Rapping",
  "Reed instrument",
  "Sampled artist",
  "Sampler",
  "Saxophone",
  "Shaker",
  "Singing & vocals",
  "Sitar",
  "Snare drum",
  "Special guest",
  "Steel drums",
  "String instrument",
  "Supporting performer",
  "Synthesizer",
  "Tabla",
  "Tambourine",
  "Theremin",
  "Timpani",
  "Triangle",
  "Trombone",
  "Trumpet",
  "Tuba",
  "Turntable",
  "Ukulele",
  "Unknown",
  "Vibraphone",
  "Viola",
  "Violin",
  "Vocal accompaniment",
  "Washboard",
  "Wind instrument",
  "Xylophone"
];

export const DISTROKID_PRODUCER_ROLES = [
  "Additional engineer",
  "Artist background vocal engineer",
  "Artist vocal second engineer",
  "Assistant producer",
  "Beat maker",
  "Co-executive producer",
  "Co-producer",
  "Digital audio workstation engineer",
  "Digital editing engineer",
  "Digital editing second engineer",
  "Direct stream digital engineer",
  "Engineer",
  "Executive producer",
  "Film sound engineer",
  "Immersive mix engineer",
  "Mastering engineer",
  "Mastering second engineer",
  "Mixing engineer",
  "Overdub engineer",
  "Overdub second engineer",
  "Post-producer",
  "Pre-production",
  "Pre-production engineer",
  "Producer",
  "Production company",
  "Production manager",
  "Programming engineer",
  "Recording engineer",
  "Recording second engineer",
  "Reissue producer",
  "Remixing engineer",
  "Remixing second engineer",
  "Second engineer",
  "String engineer",
  "Tracking engineer",
  "Tracking second engineer",
  "Transfers and safeties engineer",
  "Transfers and safeties second engineer",
  "Vocal engineer"
];

export const LOGO_LIGHT = "/logolight.png";
export const LOGO_DARK = "/logodark.png";
